### ISSUE TITLE
Can't access my passwords anymore :-(

### ISSUE THREAD

**Issue by emanchado** [copiousfreetime/keybox#10]
Hi,

I've been using keybox for years, and suddenly I stopped being able to make any changes to the database. It would print all the messages saying that it had added/modified the given entries, and at the end, a "Database not modified" and no changes at all. I was using 1.2.1 at the time, so I tried to upgrade to 1.3.0 and see if it helped.

It did allow me to add new entries, but now I can't get any passwords out of it. The --list command works, but trying to show any entries ends with the following error after accepting my password:

```
Error: invalid byte sequence in UTF-8
```

It doesn't seem to make any difference which entry I try to show (one with pure ASCII or non-ASCII characters, the new one created by keybox 1.3.0 or old ones, etc). Any ideas?

**Comment by copiousfreetime** [comment]
Hmm.. Have you upgraded ruby at all during this same time?

**Comment by copiousfreetime** [comment]
Also, I have some code since 1.3.0 that helps with ruby 2.0 and encoding issues, if you are now on ruby 2.0 it might be good to use what is in the gitrepo. I haven't pushed a new version publicly yet, but I could push a pre-release that you could attempt to use.

There is now a commandline program to upgrade a database from ruby 1.8 / 1.9  encodings to ruby 2.0 encodings, it may solve your problem.

**Comment by emanchado** [comment]
Ruby may have been updated in all the years I've been using keybox, yes, but somehow I doubt it was a Ruby upgrade what made keybox suddenly stop modifying the database. I'm just using whatever Ubuntu ships with (1.9.1, and at least in Precise it was the same version).

The shebang in the script points to /usr/bin/ruby1.9.1 so I don't think upgrading the database to ruby 2.0-style encoding will help :-( But if you want, I can make a backup and give it a try.

And just now I realise that ruby1.9.1, for some reason, points now to Ruby 1.9.3 (!!!). I don't know if that was the case before. Could that be that Ubuntu upgraded to 1.9.3 and that change made keybox not work?

Also, I have tried the upgrade script and I get:

```
Copying data to new database new-database.yaml
Saving new-database.yaml
/usr/lib/ruby/1.9.1/psych/visitors/yaml_tree.rb:15: stack level too deep (SystemStackError)
```

Any more ideas?

**Comment by copiousfreetime** [comment]
I wouldn't worry about the 1.9.1 to 1.9.3, ruby 1.9.3 is ABI compatible with ruby 1.9.1 so that should be fine.

From a data recovery perspective, I would say, make sure you have a few backups, I don't want us to accidentally destroy anything. If you are using git to store the database, or you have dropbox with extended version history, or some other continually backed up system, we should attempt to use various different older versions of you database and see when it became unreadable.

Another approach is to download and install an old version of ruby, say the last ruby-1.8.7 version and compile it from source and then install rubygems and keybox into that version of ruby and attempt to read the database. I would use something like https://github.com/postmodern/ruby-install to install the old version of ruby.  I'm not sure if this will work or not, but it will help us eliminate a ruby issue and point to either a bug in keybox or a accidental file / disk corruption issue.

Additionally, if you can replicate the issue with a sample database and send it to me, I will dig in on it.

**Comment by emanchado** [comment]
Unfortunately I can't seem to be able to install any ruby 1.8.7 with ruby-install, but I could install it using rvm.

I installed the keybox rubygem using ruby 1.8.7 and it worked like a charm. It's even able to read the new password added by the newer keybox (that was added using ruby 1.9.3), and add more passwords.

Are there any other experiments you would like me to make?

**Comment by copiousfreetime** [comment]
I'm glad you were able to recover your data. That is the most important thing.

I would love to be able to solve this bug, and if you can get me a sample database that demonstrates this error I will be happy to find the solution.

Just to make sure we are on the right page, you currently have it all working with ruby 1.8.7 and keybox 1.2.1 and if you take the same database and use it with ruby 1.9.3 or later and keybox 1.3 or later, it blows up attempting to read it?

I think these are a couple of experiments to try:
1. change the password and see if that has an effect.
2. validate the matrix of ruby and keybox version that cause the error. i.e. ruby 1.8.7, keybox 1.2.1 works, ruby 1.8.7 and keybox 1.3.0 fails, ruby 1.9.3, keybox 1.2.1 fails, etc.
3. see if you can track down which entry in the database is the one that is causing the error. Delete entries using 1.8.7 until it reads in 1.9.3 and you'll know which entry it was that caused it, and then attempt to use the data that was in that entry to create a sample database in 1.8.7 and send to me.
4. I'm going to write a ruby script tonight or tomorrow to help to track down which line of code in keybox causes the error and post it here so you can use it and send me the output.

That's all I can think of at the moment.

**Comment by emanchado** [comment]
1. Changing the password has no effect, everything works as it should (using Ruby 1.8.7 with keybox 1.3.0).
2. The difference for me seems to be caused by the ruby version. I even tried installing 1.9.1 and 1.9.3 from rvm (just in case there's something with my Ubuntu Ruby installation) to no avail: both keybox 1.2.1. and 1.3.0 work under 1.8.7, and neither 1.2.1 or 1.3.0 work under 1.9.x.
3. I have found the culprit! I had a very, very old password containing a non-ASCII character (had totally forgotten about it, sorry!). It's so old that it may have been created when my machine was still configured as iso-8859-1, so that might be the problem.
4. If you still need me to run the script to find the line, just give me a shout.

If you want to try with the specific character just in case, it was "ñ".

**Comment by emanchado** [comment]
I forgot to mention that the reason why I suspect that password might have been created as iso-8859-1 is that when showing that password, Ruby 1.8.7 shows a broken character...

**Comment by copiousfreetime** [comment]
Good to know. I would suggest removing that entry from the database in 1.8.7, then updating to ruby 2.1.2 with keybox 1.3 and using the `keybox-db-upgrade` script to update the keybox db and use it that way from now on.

Thanks for reporting this and i've opened up a new ticket to track the non-utf8 issue, see #11
